# Project information
site_name: Homer
site_url: https://bastienwirtz.github.io/

# Repository
repo_name: bastienwirtz/homer
repo_url: https://github.com/bastienwirtz/homer
edit_uri: ""

# Custom CSS
extra_css:
  - stylesheets/open-props.1.3.16.min.css
  - stylesheets/styles.css

# Theme
theme:
  favicon: images/logo.png
  logo: images/logo.png
  name: material
  # custom_dir: docs/overrides/
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to light mode
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

# Copyright - name for footer text
copyright: Homer

# Socials
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bastienwirtz/homer
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/homer-dashboard/community
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/b4bz/homer

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Page tree
nav:
  - What is Homer: index.md
  - Getting started: getting_started.md
  - Configuration: configuration.md
  - Custom services: custom_services.md
  - Tips & tricks: tips_and_tricks.md
  - Development: development.md
  - Troubleshooting: troubleshooting.md
