# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: ""
subtitle: "Ent Web |"

header: false
footer: false

defaults:
  layout: list # Either 'columns', or 'list'
  colorTheme: dark # One of 'auto', 'light', or 'dark'

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

links:
  - name: "Desktop"
    #Change Youtube Mobile page (usually happens automatically in TVBox) to Youtube Desktop page
    icon: "fa-brands fa-youtube"
#    icon: "fab fa-youtube-square"
    url: "https://www.youtube.com/index?persist_app=1&app=desktop"

services:
  - name: "Ent Web"
    icon: "fas fa-cloud-sun"
    items:
      - name: "JellyFin"
        logo: "./assets/tools/jellyfin.svg"
        url: "http://192.168.1.1:8096"
        #target: "_blank"
      - name: "TV2"
        logo: "./assets/tools/TV2.png"
        url: "https://rtmklik.rtm.gov.my/tv/2"
        #target: "_blank"
      - name: "TV3, NTV7, 8TV"
        logo: "./assets/tools/Tonton.png"
        url: "https://www.xtra.com.my/live-tv/"
        #target: "_blank"

  - name: "Youtube Playlist"
    icon: "fa-brands fa-youtube"
    items:
      - name: "Playlist"
        logo: "./assets/tools/youtube.svg"
        #subtitle: "WebUI for Rclone"
        url: "https://www.youtube.com/playlist?list=PLzcpmqe6SErl1qCMtZwqq2tSoQGyTaNkq"
        #target: "_blank"
      - #For Custom Created Youtube Playlist
        name: "东宫"
        logo: "https://www.i0856.com/annex/vod/2022-02/07/7897c8f970701cd17a1a896d6309591c.jpg"
        url: "https://www.youtube.com/playlist?list=PL0Rq7IGOfym6wgrz0Q9UA39_D7mtm0RZ4"
        #url: "https://www.i0856.com/play/9325.html"
